FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=12345678
ENV POSTGRES_DB=db_dskola

# if you want to check the result on local
EXPOSE 5432

COPY ./init_db/init.sql /docker-entrypoint-initdb.d/
COPY insertData.sql /docker-entrypoint-initdb.d/