FROM python:3.9-slim

RUN apt-get update && apt-get install -y postgresql-client

RUN pip install pandas

COPY /source_data/ /usr/src/
COPY load_data.py /usr/src/load_data.py

WORKDIR /usr/src

CMD ["python3", "load_data.py"]

#COPY ./init_db/insertData.sql /docker-entrypoint-initdb.d/